spring:
  application:
    name: aggregate-search-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregate-search-dev
    driver-class-name: org.postgresql.Driver
    username: qianfang
server:
  port: 8080
  servlet:
    context-path: /api