/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ArticlePageList: typeof import('./src/components/ArticlePageList.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter.vue')['default']
    PageList: typeof import('./src/components/PageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
  }
}
